# Generated by Django 5.0.7 on 2025-02-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_management', '0003_server_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=255)),
                ('script_type', models.CharField(choices=[('python', 'Python Script'), ('shell', 'Shell Script')], max_length=20)),
                ('script_path', models.CharField(max_length=1024)),
                ('execute_time', models.DateTimeField()),
                ('execute_count', models.IntegerField(default=1)),
                ('is_recurring', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='server_management.server')),
            ],
        ),
    ]
