/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alarm_set: typeof import('./src/components/Alarm_set.vue')['default']
    Alarm_set_from: typeof import('./src/components/Alarm_set_from.vue')['default']
    AlarmForm: typeof import('./src/components/AlarmForm.vue')['default']
    AlarmTask: typeof import('./src/components/AlarmTask.vue')['default']
    AlarmTaskForm: typeof import('./src/components/AlarmTaskForm.vue')['default']
    copy: typeof import('./src/components/userinfo copy.vue')['default']
    Diniao: typeof import('./src/components/Diniao.vue')['default']
    'Diniao copy': typeof import('./src/components/Diniao copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMemuItem: typeof import('element-plus/es')['ElMemuItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Logdatacollection: typeof import('./src/components/Logdatacollection.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Loginformationdisplay: typeof import('./src/components/Loginformationdisplay.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Serverfrom_data: typeof import('./src/components/Serverfrom_data.vue')['default']
    ServerMonitoring: typeof import('./src/components/ServerMonitoring.vue')['default']
    ServerTerminal: typeof import('./src/components/ServerTerminal.vue')['default']
    'ServerTerminal copy': typeof import('./src/components/ServerTerminal copy.vue')['default']
    Userinfo: typeof import('./src/components/userinfo.vue')['default']
    'Userinfo copy': typeof import('./src/components/userinfo copy.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
