# Generated by Django 5.0.7 on 2024-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="example@example.com", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
