# Generated by Django 5.0.7 on 2024-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
