# Generated by Django 5.0.7 on 2024-08-24 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="服务器名称")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 地址")),
                ("port", models.PositiveIntegerField(verbose_name="端口号")),
                (
                    "operating_system",
                    models.CharField(max_length=100, verbose_name="操作系统"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建日期"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日期"),
                ),
                (
                    "encrypted_password",
                    models.BinaryField(blank=True, null=True, verbose_name="加密密码"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="拥有者",
                    ),
                ),
            ],
        ),
    ]
