# Generated by Django 5.0.7 on 2024-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_management", "0002_alter_server_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="user",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="用户名"
            ),
        ),
    ]
