# Generated by Django 5.0.7 on 2025-02-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("server_management", "0003_server_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_type",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU 使用率"),
                            ("memory", "内存使用率"),
                            ("disk", "磁盘空间"),
                            ("network", "网络带宽"),
                        ],
                        max_length=10,
                        verbose_name="报警类型",
                    ),
                ),
                (
                    "alarm_level",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        max_length=10,
                        verbose_name="报警级别",
                    ),
                ),
                ("threshold", models.FloatField(verbose_name="报警阈值")),
                (
                    "current_value",
                    models.FloatField(blank=True, null=True, verbose_name="当前值"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("triggered", "已触发"),
                            ("resolved", "已处理"),
                            ("pending", "待处理"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="报警状态",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="报警信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_tasks",
                        to="server_management.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
        ),
    ]
