# Generated by Django 5.0.7 on 2025-02-10 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alarm_set", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alarmtask",
            old_name="alarm_level",
            new_name="alarmLevel",
        ),
        migrations.RenameField(
            model_name="alarmtask",
            old_name="alarm_type",
            new_name="alarmType",
        ),
        migrations.RenameField(
            model_name="alarmtask",
            old_name="server",
            new_name="serverId",
        ),
    ]
