# Generated by Django 5.0.7 on 2024-09-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("server_management", "0003_server_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("log_level", models.CharField(max_length=10)),
                ("message", models.TextField()),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="server_management.server",
                    ),
                ),
            ],
            options={
                "unique_together": {("server", "timestamp")},
            },
        ),
    ]
